name: pusher_beams_web
description: The Web implementation from Pusher Beams for Flutter, intended to be a platform-specific package.
version: 1.2.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1
  pusher_beams_platform_interface: ^1.2.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: pusher_beams
    platforms:
      web:
        pluginClass: PusherBeams
        fileName: pusher_beams_web.dart
