name: pusher_beams
description: Unofficial Flutter Plugin for Pusher Beams, receive notifications easily on your Flutter application with Pusher Beams.
version: 1.2.1
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pusher_beams_android:
    path: ../pusher_beams_android
  pusher_beams_ios:
    path: ../pusher_beams_ios
  pusher_beams_platform_interface:
    path: ../pusher_beams_platform_interface
  uuid: ^4.5.0

dev_dependencies:
  analyzer: ^6.4.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

flutter:
  plugin:
    platforms:
      android:
        default_package: pusher_beams_android
      ios:
        default_package: pusher_beams_ios
      web:
        default_package: pusher_beams_web
