name: pusher_beams_android
description: The Android implementation from Pusher Beams for Flutter, intended to be a platform-specific package.
version: 1.2.0
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pusher_beams_platform_interface:
    path: ../pusher_beams_platform_interface

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: pusher_beams
    platforms:
      android:
        package: com.pusher.pusher_beams
        pluginClass: PusherBeamsPlugin
