// Autogenerated from Pigeon (v22.4.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class PGNBeamsAuthProvider;

@interface PGNBeamsAuthProvider : NSObject
+ (instancetype)makeWithAuthUrl:(nullable NSString *)authUrl
    headers:(nullable NSDictionary<NSString *, NSString *> *)headers
    queryParams:(nullable NSDictionary<NSString *, NSString *> *)queryParams
    credentials:(nullable NSString *)credentials;
@property(nonatomic, copy, nullable) NSString * authUrl;
@property(nonatomic, copy, nullable) NSDictionary<NSString *, NSString *> * headers;
@property(nonatomic, copy, nullable) NSDictionary<NSString *, NSString *> * queryParams;
@property(nonatomic, copy, nullable) NSString * credentials;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *PGNGetMessagesCodec(void);

@protocol PGNPusherBeamsApi
- (void)startInstanceId:(NSString *)instanceId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)getInitialMessageWithCompletion:(void (^)(NSDictionary<NSString *, NSObject *> *_Nullable, FlutterError *_Nullable))completion;
- (void)addDeviceInterestInterest:(NSString *)interest error:(FlutterError *_Nullable *_Nonnull)error;
- (void)removeDeviceInterestInterest:(NSString *)interest error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<NSString *> *)getDeviceInterestsWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setDeviceInterestsInterests:(NSArray<NSString *> *)interests error:(FlutterError *_Nullable *_Nonnull)error;
- (void)clearDeviceInterestsWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)onInterestChangesCallbackId:(NSString *)callbackId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setUserIdUserId:(NSString *)userId provider:(PGNBeamsAuthProvider *)provider callbackId:(NSString *)callbackId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)clearAllStateWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)onMessageReceivedInTheForegroundCallbackId:(NSString *)callbackId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)onMessageReceivedInTheBackgroundCallbackId:(NSString *)callbackId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpPGNPusherBeamsApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNPusherBeamsApi> *_Nullable api);

extern void SetUpPGNPusherBeamsApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNPusherBeamsApi> *_Nullable api, NSString *messageChannelSuffix);


@interface PGNCallbackHandlerApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)handleCallbackCallbackId:(NSString *)callbackId callbackName:(NSString *)callbackName args:(NSArray<id> *)args completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
