name: pusher_beams_platform_interface
description: A common platform interface from Pusher Beams for Flutter, intended to be the platform interface package.
version: 1.2.0
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^22.4.0
  mockito: ^5.4.4
